// Generated by scripts/build-abis.mjs from contracts/DeskArena.sol — do not edit by hand.
export const deskArenaAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "pool_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "registry_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "sessionKey_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyVoted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ArenaFull",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadBond",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadChoice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadName",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "BadgesAlreadySet",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoDesk",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotDeployer",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RefundFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Retired",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "int256",
        "name": "points",
        "type": "int256"
      }
    ],
    "name": "BallotSettled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "bond",
        "type": "uint256"
      }
    ],
    "name": "DeskCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "choice",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "mid",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "int256",
        "name": "cashE6",
        "type": "int256"
      },
      {
        "indexed": false,
        "internalType": "int256",
        "name": "baseE6",
        "type": "int256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "armed",
        "type": "bool"
      }
    ],
    "name": "DeskExecuted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "wantsLive",
        "type": "bool"
      }
    ],
    "name": "DeskLiveChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "owner",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "bondReturned",
        "type": "uint256"
      }
    ],
    "name": "DeskRetired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "int256",
        "name": "bps",
        "type": "int256"
      },
      {
        "indexed": false,
        "internalType": "int64",
        "name": "bidPts",
        "type": "int64"
      },
      {
        "indexed": false,
        "internalType": "int64",
        "name": "askPts",
        "type": "int64"
      },
      {
        "indexed": false,
        "internalType": "int64",
        "name": "holdPts",
        "type": "int64"
      }
    ],
    "name": "RoundScored",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "mid",
        "type": "uint256"
      }
    ],
    "name": "Ticked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "choice",
        "type": "uint8"
      }
    ],
    "name": "Voted",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ASK",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "AUTO_SETTLE",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "BID",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "CREATE_BOND",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "HOLD",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "HOLD_POINTS",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "LOT_E6",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_DESKS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_POINTS",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_POSITION_LOTS",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "NONE",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PLACE_ORDER_FOR",
    "outputs": [
      {
        "internalType": "bytes4",
        "name": "",
        "type": "bytes4"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "ROUND_SECONDS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SEASON_ROUNDS",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "START_CASH_E6",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "arenaState",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "roundId",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "endsAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "lastTickedRound",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "mid",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "season",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "seasonRound",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "deskCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "voterCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "createBond",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "sessionKey",
            "type": "address"
          }
        ],
        "internalType": "struct DeskArena.ArenaState",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "badgesSet",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "contributorBadge",
    "outputs": [
      {
        "internalType": "contract IArenaBadge",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "offset",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "limit",
        "type": "uint256"
      }
    ],
    "name": "contributorBoard",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "wallet",
            "type": "address"
          },
          {
            "internalType": "int256",
            "name": "points",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "seasonPoints",
            "type": "int256"
          },
          {
            "internalType": "uint32",
            "name": "ballotsCast",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "roundsScored",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "streak",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "bestStreak",
            "type": "uint32"
          },
          {
            "internalType": "uint64",
            "name": "lastVotedRound",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "pending",
            "type": "uint256"
          }
        ],
        "internalType": "struct DeskArena.ContributorView[]",
        "name": "board",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "contributorScoreOf",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "wallet",
        "type": "address"
      }
    ],
    "name": "contributorView",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "wallet",
            "type": "address"
          },
          {
            "internalType": "int256",
            "name": "points",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "seasonPoints",
            "type": "int256"
          },
          {
            "internalType": "uint32",
            "name": "ballotsCast",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "roundsScored",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "streak",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "bestStreak",
            "type": "uint32"
          },
          {
            "internalType": "uint64",
            "name": "lastVotedRound",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "pending",
            "type": "uint256"
          }
        ],
        "internalType": "struct DeskArena.ContributorView",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "createDesk",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentRound",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentSeason",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "deployer",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "deskBadge",
    "outputs": [
      {
        "internalType": "contract IArenaBadge",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "deskBoard",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "deskId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "int256",
            "name": "cashE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "baseE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "pnlE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "seasonPnlE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "equityE6",
            "type": "int256"
          },
          {
            "internalType": "uint64",
            "name": "createdRound",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "roundsTraded",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "wins",
            "type": "uint32"
          },
          {
            "internalType": "bool",
            "name": "armed",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "wantsLive",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "retired",
            "type": "bool"
          },
          {
            "internalType": "uint32",
            "name": "bid",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "ask",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "hold",
            "type": "uint32"
          }
        ],
        "internalType": "struct DeskArena.DeskView[]",
        "name": "board",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "deskCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "name": "deskIsArmed",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "deskScoreOf",
    "outputs": [
      {
        "internalType": "int256",
        "name": "best",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "deskView",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "deskId",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "int256",
            "name": "cashE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "baseE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "pnlE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "seasonPnlE6",
            "type": "int256"
          },
          {
            "internalType": "int256",
            "name": "equityE6",
            "type": "int256"
          },
          {
            "internalType": "uint64",
            "name": "createdRound",
            "type": "uint64"
          },
          {
            "internalType": "uint32",
            "name": "roundsTraded",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "wins",
            "type": "uint32"
          },
          {
            "internalType": "bool",
            "name": "armed",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "wantsLive",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "retired",
            "type": "bool"
          },
          {
            "internalType": "uint32",
            "name": "bid",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "ask",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "hold",
            "type": "uint32"
          }
        ],
        "internalType": "struct DeskArena.DeskView",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "desksOf",
    "outputs": [
      {
        "internalType": "uint256[]",
        "name": "",
        "type": "uint256[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "genesisRound",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lastTickedRound",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "liveMid",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "myVote",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "pendingBallots",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "pool",
    "outputs": [
      {
        "internalType": "contract ISpotPool",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "registry",
    "outputs": [
      {
        "internalType": "contract IOperatorRegistry",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "name": "retireDesk",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "roundEndsAt",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "roundMid",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "roundScore",
    "outputs": [
      {
        "internalType": "int64",
        "name": "bidPts",
        "type": "int64"
      },
      {
        "internalType": "int64",
        "name": "askPts",
        "type": "int64"
      },
      {
        "internalType": "int64",
        "name": "holdPts",
        "type": "int64"
      },
      {
        "internalType": "bool",
        "name": "settled",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      }
    ],
    "name": "seasonOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "name": "seasonPnlOf",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      }
    ],
    "name": "seasonPointsOf",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "secondsLeft",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "sessionKey",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "desk_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "contributor_",
        "type": "address"
      }
    ],
    "name": "setBadges",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "wantsLive",
        "type": "bool"
      }
    ],
    "name": "setWantsLive",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "voter",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "maxBallots",
        "type": "uint256"
      }
    ],
    "name": "settle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "settleCursor",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "name": "tallyOf",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "tick",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "choice",
        "type": "uint8"
      }
    ],
    "name": "vote",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "voterCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "roundId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "deskId",
        "type": "uint256"
      }
    ],
    "name": "winnerOf",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;
