import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile } from "./lib/compile.mjs";
import { ROOT } from "./lib/env.mjs";

/** Keeps src/lib/chain/*-abi.ts generated from contracts/ so the two never drift. */
const targets = [
  ["DeskArena.sol", "DeskArena", "arena-abi.ts", "deskArenaAbi"],
  ["ArenaBadge.sol", "ArenaBadge", "arena-badge-abi.ts", "arenaBadgeAbi"],
  ["ArenaClock.sol", "ArenaClock", "arena-clock-abi.ts", "arenaClockAbi"],
  ["StakePool.sol", "StakePool", "stake-pool-abi.ts", "stakePoolAbi"],
];

for (const [file, name, out, exportName] of targets) {
  const { abi } = compile(file, name);
  const body = `// Generated by scripts/build-abis.mjs from contracts/${file} — do not edit by hand.\nexport const ${exportName} = ${JSON.stringify(
    abi,
    null,
    2,
  )} as const;\n`;
  writeFileSync(join(ROOT, "src/lib/chain", out), body);
  console.log(`src/lib/chain/${out}  (${abi.length} entries)`);
}
